### ISSUE TITLE
remove_favorite raise an error when cache is enabled

### ISSUE THREAD

**Issue by kumekay** [jonhue/acts_as_favoritor#30]
`remove_favorite` raise NoMethodError when cache is enabled and method called on object that is not liked
tv - acts_as_favoritable
u -  acts_as_favoritor

**To Reproduce**
```
u.favorite(tv) # Ok
u.remove_favorite(tv) # Ok
u.remove_favorite(tv) # Fail
NoMethodError: undefined method `-' for nil:NilClass
```

gem 0.2.1

**Comment by jonhue** [comment]
Please update to 2.1.0

**Comment by RonWalker22** [comment]
@jonhue this bug was never fixed. I assume kumekay was referring to gem version 2.1.0 as 0.2.1 does not exist. I have fixed the issue here  https://github.com/RonWalker22/acts_as_favoritor/commit/1690d144232616a8205c2af14baa3b3e183ba2ba#diff-d7faf63a7450a9f40a5e2cd1b0f6570d

While i was doing the fix, I noticed the remove_favorite method could be DRY'd up. So I also did that here https://github.com/RonWalker22/acts_as_favoritor/commit/779d2b7713e0d05980f7ab8897dd70e365cfd089

I had to put the commits on a different branch because I'm not sure how to toggle the cache on for certain tests. I tried `ActsAsFavoritor.configuration.cache = true` and it doesn't work. Let me know how I can do that, then I can create the pull requests.

**Comment by RonWalker22** [comment]
The config value changes, but the test fails when that is all that you change. So there's another bug somewhere. 

So with 
1. `config.cache = false` in the initialize file
2. a setup method in one of the test with `ActsAsFavoritor.configuration.cache = true`
3. a teardown method inside same test with `ActsAsFavoritor.configuration.cache = false`

There are errors with that test. Try to do one of these kinds of tests and let me know what you get.
